name: Terraform

on:
  push:
    branches: [ "main" ]         # Run on post-merge to main

jobs:
  terraform:
    name: 'Terraform CI'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
           TF_VAR_okta_private_key: ${{ secrets.TF_VAR_okta_private_key }}
           TF_VAR_okta_client_id: ${{ secrets.TF_VAR_okta_client_id }}
          

      # Optional: Terraform Apply (Usually for tagged releases or with manual approval)
